from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from starbridge_mcp.core.security import sanitize


@dataclass(frozen=True)
class ToolCapability:
    name: str
    bridge: str
    action: str
    maturity: str
    risk_level: str
    description: str
    side_effects: str
    safe_default: bool
    requires_confirmation: bool
    requires_local_software: bool
    source_projects: tuple[str, ...] = field(default_factory=tuple)
    invocation: str | None = None
    next_step: str | None = None
    categories: tuple[str, ...] = field(default_factory=tuple)

    @property
    def current_status(self) -> str:
        if self.maturity in {"implemented", "prototype"}:
            return "stable"
        if self.maturity in {"experimental", "experimental_demo", "research"}:
            return "experimental"
        if self.maturity == "planned":
            return "planned"
        return "not implemented"

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "bridge": self.bridge,
            "action": self.action,
            "maturity": self.maturity,
            "current_status": self.current_status,
            "risk_level": self.risk_level,
            "description": self.description,
            "side_effects": self.side_effects,
            "safe_default": self.safe_default,
            "requires_confirmation": self.requires_confirmation,
            "requires_local_software": self.requires_local_software,
            "source_projects": list(self.source_projects),
            "invocation": self.invocation,
            "next_step": self.next_step,
            "categories": list(self.categories),
        }


CAPABILITIES: tuple[ToolCapability, ...] = (
    ToolCapability(
        name="starbridge.status",
        bridge="all",
        action="status",
        maturity="implemented",
        risk_level="safe_read_only",
        description="返回所有本地创意软件 bridge 的统一状态摘要。",
        side_effects="只读取环境变量和本机服务状态；不会打开用户文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("GLips/Figma-Context-MCP", "IO-AtelierTech/comfyui-mcp"),
        invocation="python -m starbridge_mcp.server status --json",
    ),
    ToolCapability(
        name="starbridge.tools",
        bridge="all",
        action="tools",
        maturity="implemented",
        risk_level="safe_read_only",
        description="列出 StarBridge 当前可用、实验中和计划中的安全工具能力。",
        side_effects="只返回静态能力清单。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "ie3jp/illustrator-mcp-server"),
        invocation="python -m starbridge_mcp.server tools --json",
        categories=("discovery",),
    ),
    ToolCapability(
        name="starbridge.evidence_init",
        bridge="all",
        action="evidence_init",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Initialize a sanitized EvidenceManifest summary and optional local manifest path under examples/output/evidence.",
        side_effects="Safe by default; CLI may write only ignored JSON under examples/output/evidence and never launches desktop software.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "00bx/00bx-photoshop-mcp"),
        invocation="python -m starbridge_mcp.server evidence --init --json",
        categories=("evidence", "planning"),
    ),
    ToolCapability(
        name="starbridge.evidence_validate",
        bridge="all",
        action="evidence_validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Validate EvidenceManifest status vocabulary, field shape, and sanitized output boundaries.",
        side_effects="Read-only validation for manifests stored under examples/output/evidence.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
        invocation="python -m starbridge_mcp.server evidence --validate --json",
        categories=("validation", "evidence"),
    ),
    ToolCapability(
        name="starbridge.job_status",
        bridge="all",
        action="job_status",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Return a unified queued/running/completed/failed/cancelled/needs_user job status view backed by EvidenceManifest data.",
        side_effects="Read-only status synthesis; no desktop launch and no private file reads.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "IO-AtelierTech/comfyui-mcp"),
        invocation="python -m starbridge_mcp.server job-status --json",
        categories=("execution", "evidence"),
    ),
    ToolCapability(
        name="cad_autocad.environment_probe",
        bridge="cad_autocad",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查 AutoCAD 可执行文件、COM 注册和 pywin32 线索。",
        side_effects="不打开 DWG/DXF，不控制 CAD 软件，不写文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp", "AnCode666/multiCAD-mcp"),
        invocation="python examples/cad_bridge/probe.py --json",
    ),
    ToolCapability(
        name="autocad_dxf.status",
        bridge="autocad_dxf",
        action="status",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查离线 DXF bridge 是否能做 CAD plan 校验和 dry-run。",
        side_effects="不需要 AutoCAD，不打开 DWG/DXF。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp",),
        invocation="python examples/cad/generate_dxf_plan.py --dry-run",
    ),
    ToolCapability(
        name="autocad_dxf.validate_cad_plan",
        bridge="autocad_dxf",
        action="validate_cad_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验 CAD JSON plan 的单位、图层和实体结构。",
        side_effects="只处理传入 JSON，不写文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp", "AnCode666/multiCAD-mcp"),
    ),
    ToolCapability(
        name="autocad_dxf.write_dxf",
        bridge="autocad_dxf",
        action="write_dxf",
        maturity="implemented",
        risk_level="guarded_local_write",
        description="把已校验 CAD plan 写成测试 DXF；默认应该先 dry-run。",
        side_effects="dry_run=False 时只允许写入 examples/cad/output。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp",),
        next_step="保持真实 AutoCAD COM/MCP 控制与离线 DXF export 分离。",
    ),
    ToolCapability(
        name="comfyui.system_probe",
        bridge="comfyui",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="读取 ComfyUI /system_stats 与 /object_info，确认服务和节点是否可用。",
        side_effects="只访问本机或配置的 ComfyUI API，不提交生成任务。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
        invocation="python examples/comfy_bridge/probe.py --json",
    ),
    ToolCapability(
        name="comfyui.workflow_validate",
        bridge="comfyui",
        action="workflow_validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验 workflow JSON 是否为 API format，并检查关键节点引用。",
        side_effects="只读取公开示例 workflow 或用户明确传入的文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
        invocation="python examples/comfy_bridge/validate_workflow.py --json",
    ),
    ToolCapability(
        name="comfyui.workflow_build_plan",
        bridge="comfyui",
        action="workflow_build_plan",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Plan a ComfyUI txt2img, img2img, inpaint, or upscale workflow from a natural-language goal without generating or submitting a job.",
        side_effects="Dry-run only; does not scan disks, read models, or contact ComfyUI.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfyui.workflow_build",
        bridge="comfyui",
        action="workflow_build",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Generate a valid API-format ComfyUI txt2img workflow JSON with placeholders and a workflow hash.",
        side_effects="Dry-run only; does not submit to ComfyUI and does not write files.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_draft",
        bridge="comfyui",
        action="workflow_draft",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Generate API-like draft workflow JSON for txt2img, img2img, inpaint, or upscale with placeholder-only assets.",
        side_effects="Draft only; does not read files, discover models, make network requests, or submit to ComfyUI.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_compose",
        bridge="comfyui",
        action="workflow_compose",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Compose API-like ComfyUI workflow JSON from safe placeholder graph modules.",
        side_effects="Composer only; does not read files, discover models, make network requests, or submit to ComfyUI.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_template_list",
        bridge="comfyui",
        action="workflow_template_list",
        maturity="prototype",
        risk_level="safe_read_only",
        description="List bundled ComfyUI workflow templates and template lint status.",
        side_effects="Reads only the public registry metadata bundled in examples; does not read private files, use network, or submit queue jobs.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_template_get",
        bridge="comfyui",
        action="workflow_template_get",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Return one bundled ComfyUI workflow template by template_id with lint status.",
        side_effects="Reads only public registry metadata; does not read private files, use network, or submit queue jobs.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_from_template",
        bridge="comfyui",
        action="workflow_from_template",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Compose placeholder-only API-like ComfyUI workflow JSON from a bundled template.",
        side_effects="Uses safe graph composer modules only; does not read private files, use network, or submit queue jobs.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfyui.workflow_repair",
        bridge="comfyui",
        action="workflow_repair",
        maturity="prototype",
        risk_level="safe_read_only",
        description="Repair missing txt2img nodes, bad sampler values, invalid dimensions, prompt text, and core links.",
        side_effects="Dry-run only; returns repaired JSON and validation metadata without submitting to ComfyUI.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfyui.agent_run",
        bridge="comfyui",
        action="agent_run",
        maturity="prototype",
        risk_level="guarded_local_process",
        description="Build, validate, repair, and only with confirm_run=true submit a generated txt2img workflow to local ComfyUI.",
        side_effects="Default is dry-run; confirmed runs contact local ComfyUI and may cause ComfyUI to write images to its configured output directory.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
        next_step="Keep img2img, inpaint, and upscale as dry-run plans until reviewed safe workflow templates exist.",
    ),
    ToolCapability(
        name="photoshop.session_info",
        bridge="photoshop",
        action="session_info",
        maturity="prototype",
        risk_level="safe_read_only",
        description="通过 Windows COM 读取 Photoshop session 和当前文档摘要。",
        side_effects="需要已授权 Photoshop；不打开 PSD，不保存导出。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server", "alisaitteke/photoshop-mcp"),
        invocation="powershell -ExecutionPolicy Bypass -File examples/photoshop_bridge/scripts/document_info.ps1",
    ),
    ToolCapability(
        name="photoshop.document_info",
        bridge="photoshop",
        action="document_info",
        maturity="experimental_demo",
        risk_level="safe_read_only",
        description="Read active Photoshop document metadata through COM without opening private PSD files.",
        side_effects="Requires an authorized local Photoshop session; does not save or export files.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:info",
    ),
    ToolCapability(
        name="photoshop.create_demo_document",
        bridge="photoshop",
        action="create_demo_document",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Create a public sandbox Photoshop layer demo.",
        side_effects="dry_run is the default; real output requires confirm_write and is restricted to examples/output/photoshop.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:demo:plan",
    ),
    ToolCapability(
        name="photoshop.export_demo_preview",
        bridge="photoshop",
        action="export_demo_preview",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Export PNG and JPG previews from the Photoshop sandbox demo only.",
        side_effects="dry_run is the default; real export requires confirm_export and is restricted to examples/output/photoshop.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:demo",
    ),
    ToolCapability(
        name="photoshop.run_demo",
        bridge="photoshop",
        action="run_demo",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Run the Photoshop sandbox create, export, and manifest sequence.",
        side_effects="dry_run is the default; real run requires confirm_write and confirm_export.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:demo",
    ),
    ToolCapability(
        name="photoshop.subject_extract",
        bridge="photoshop",
        action="subject_extract",
        maturity="planned",
        risk_level="guarded_local_write",
        description="对用户明确传入的图片运行主体选择并导出测试 PNG。",
        side_effects="会打开输入图片并写出输出 PNG；输入和输出路径必须由参数传入。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server", "alisaitteke/photoshop-mcp"),
        next_step="后续 MCP tool 必须保留参数化路径和输出脱敏。",
    ),
    ToolCapability(
        name="illustrator.document_info",
        bridge="illustrator",
        action="document_info",
        maturity="experimental_demo",
        risk_level="safe_read_only",
        description="Read active Illustrator document, artboard, layer, page item, and text frame metadata through COM.",
        side_effects="Does not open private AI files and does not export files.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:info",
    ),
    ToolCapability(
        name="illustrator.create_demo_artboard",
        bridge="illustrator",
        action="create_demo_artboard",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Create a public sandbox Illustrator vector artboard demo.",
        side_effects="dry_run is the default; real output requires confirm_write and is restricted to examples/output/illustrator.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:demo:plan",
    ),
    ToolCapability(
        name="illustrator.export_demo_assets",
        bridge="illustrator",
        action="export_demo_assets",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Export SVG, PNG, and PDF from the Illustrator sandbox demo only.",
        side_effects="dry_run is the default; real export requires confirm_export and is restricted to examples/output/illustrator.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:demo",
    ),
    ToolCapability(
        name="illustrator.run_demo",
        bridge="illustrator",
        action="run_demo",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Run the Illustrator sandbox artboard, export, and manifest sequence.",
        side_effects="dry_run is the default; real run requires confirm_write and confirm_export.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:demo",
    ),
    ToolCapability(
        name="illustrator.preflight",
        bridge="illustrator",
        action="preflight",
        maturity="planned",
        risk_level="safe_read_only",
        description="检查当前 Illustrator 文档的印前风险，例如链接、颜色模式和文本问题。",
        side_effects="只读取当前文档信息；不修复、不保存。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        next_step="只迁移规则思想，不复制第三方 JSX 源码。",
    ),
    ToolCapability(
        name="blender.environment_probe",
        bridge="blender",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查 Blender 可执行文件和可选 MCP 目录。",
        side_effects="不打开 .blend，不运行任意 Python，不下载模型。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("ahujasid/blender-mcp",),
        invocation="python examples/blender_bridge/probe.py --json",
    ),
    ToolCapability(
        name="blender.scene_probe",
        bridge="blender",
        action="scene_probe",
        maturity="planned",
        risk_level="guarded_local_process",
        description="未来用公开安全脚本启动 Blender 生成基础测试场景并验证渲染环境。",
        side_effects="会启动 Blender 进程；不得执行任意用户脚本或下载外部资产。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ahujasid/blender-mcp",),
        next_step="先做固定模板场景，不开放任意 Python 执行。",
    ),
    ToolCapability(
        name="jianying_capcut.draft_probe",
        bridge="jianying_capcut",
        action="draft_probe",
        maturity="research",
        risk_level="safe_read_only",
        description="检查剪映/CapCut 可执行文件和草稿目录配置。",
        side_effects="不读取 draft_content.json，不导出视频，不触碰账号。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("sun-guannan/VectCutAPI", "xuliang2024/cutcli-cookbook"),
        invocation="python examples/capcut_jianying_bridge/probe.py --json",
    ),
)


BRIDGE_CAPABILITY_CATEGORIES: dict[str, list[str]] = {
    "comfyui": ["discovery", "planning", "execution", "validation", "evidence"],
    "blender": ["discovery", "planning", "validation", "evidence"],
    "autocad": ["discovery", "planning", "execution", "validation", "evidence"],
    "autocad_dxf": ["planning", "execution", "validation", "evidence", "cleanup"],
    "photoshop": ["discovery", "planning", "execution", "validation", "evidence", "cleanup"],
    "illustrator": ["discovery", "planning", "execution", "validation", "evidence", "cleanup"],
    "jianying_capcut": ["discovery", "planning", "validation", "evidence"],
    "all": ["discovery", "planning", "execution", "validation", "evidence", "cleanup"],
}


def list_capabilities(*, bridge: str = "all", include_guarded: bool = True) -> list[dict[str, Any]]:
    selected = []
    for capability in CAPABILITIES:
        if bridge != "all" and capability.bridge not in {bridge, "all"}:
            continue
        if not include_guarded and not capability.safe_default:
            continue
        selected.append(capability.to_dict())
    return sanitize(selected)


def capability_summary(*, bridge: str = "all", include_guarded: bool = True) -> dict[str, Any]:
    capabilities = list_capabilities(bridge=bridge, include_guarded=include_guarded)
    return sanitize(
        {
            "ok": True,
            "framework": "StarBridge",
            "action": "tools",
            "bridge": bridge,
            "capability_count": len(capabilities),
            "capabilities": capabilities,
            "bridge_categories": BRIDGE_CAPABILITY_CATEGORIES,
            "adoption_policy": {
                "third_party_source": "third_party_research is local-only and ignored by Git.",
                "copy_policy": "借鉴架构和接口形状；不直接复制第三方源码到公开仓库。",
                "write_policy": "写入类能力必须参数化路径、默认 dry-run 或需要用户确认。",
            },
        }
    )
